name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 15 * * *' # 毎日UTC15:00に実行(JST24:00)
  workflow_dispatch:
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set upstream remote
      run: git remote add upstream https://github.com/LideruBcgDev/ccp-airdrop.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main

    - name: Push changes to fork
      run: git push origin main
    